# Site settings
title: Tim Guo
email: tim@timguoqk.me
description: > # this means to ignore newlines until "baseurl:"
  Tim's personal website.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://timguoqk.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Other settings
permalink: none

gems:
  - octopress-autoprefixer