# Site settings
title: Tim Guo's Portfolio Page
email: tim@timguoqk.me
description: > # this means to ignore newlines until "baseurl:"
  Hi I'm Tim. First-year CS + Psychology student at UCLA.
  I aspire to build a better way to interact with the digital world.
  Though this site contains my works unrelated to this goal as well :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://timguoqk.github.io" # the base hostname & protocol for your site
twitter_username: timguoqk
github_username:  timguoqk

# Build settings
markdown: kramdown
